[package]
name = "thepalace"
version = "0.1.0"
edition = "2024"
description = "ThePalace common functionality"

[features]
default = []
prop = ["bitflags"]

[build-dependencies]
bytemuck = "1.22.0"

[dependencies]
bitflags = { version = "2.9.0", optional = true }
cfg-if = "1.0.0"
